[project]
name = "backtab"
version = "0.1.0"
description = ""
authors = [
    {name = "Arno Cornette",email = "ar.cornette@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beancount (==2.3.6)",
    "bottle (>=0.13.4,<0.14.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "click (>=8.3.0,<9.0.0)",
    "sdnotify (>=0.3.2,<0.4.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
