"""
This type stub file was generated by pyright.
"""

import unittest
from beancount.utils import encryption

__copyright__ = ...
__license__ = ...
TEST_PUBLIC_KEY = ...
TEST_SECRET_KEY = ...
INPUT = ...
class TestEncryptedBase(unittest.TestCase):
    def setUp(self): # -> None:
        ...
    
    def tearDown(self): # -> None:
        ...
    
    def run_gpg(self, *args, **kw): # -> tuple[str, str]:
        ...
    
    def encrypt_as_file(self, string, encrypted_filename): # -> None:
        ...
    


class TestEncryptedFiles(TestEncryptedBase):
    @unittest.skipIf(not encryption.is_gpg_installed(), "gpg is not installed")
    def test_read_encrypted_file(self): # -> None:
        ...
    


class TestEncryptedFilesCheck(unittest.TestCase):
    def test_is_encrypted_file(self): # -> None:
        ...
    


if __name__ == '__main__':
    ...
